name: CI Pipeline

on:
  push:
    branches: [ main ]

defaults:
  run:
    working-directory: backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Installing dependencies
        run: npm install

      - name: Linting
        run: npm run lint

      - name: Running tests
        run: npm run test