name: CI Pipeline

on:
  push:
    branches: [ main ]

defaults:
  run:
    working-directory: backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Installing dependencies
        run: npm install

      - name: Linting
        run: npm run lint

      - name: Running tests
        run: npm run test

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Building a Docker image
        working-directory: .
        run: docker compose build
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          IMAGE_TAG: ${{ github.sha }}

      - name: Push images
        working-directory: .
        run: docker compose push
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          IMAGE_TAG: ${{ github.sha }}