name: PR Tests

on:
  workflow_call:

defaults:
  run:
    working-directory: backend

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Installing dependencies
        run: npm install

      - name: Linting
        run: npm run lint

      - name: Running tests
        run: npm run test